### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by mounieju** [PolytechLyon/isi3-test-tp7-mounier-jolivet#1]
Bonjour
Pouvez-vous nous faire un retour sur notre code? 
Merci

**Comment by Slashgear** [comment]
C'est nickel,

Il est possible ici d''optimiser un peu votre approche fonctionelle 

https://github.com/PolytechLyon/isi3-test-tp7-mounier-jolivet/blob/0683fef853d220e1faa60d83294a4028be1d7bb8/fizzbuzz/src/main/java/FizzBuzz.java#L29-L32

Plutot que collect dans une list, vous pouvez récupérer le premier element de ce "flux" grâce à findFirst. Cela vous retourne un Optional<String> que vous pouvez manipuler facilement avec des opérateurs comme orElse
